BIN = ned_pg
CC = g++
FLAGS = -Wall -pedantic -fsanitize=address -std=c++17 -DLOCAL=1
INC = -I ../common/include
LOC_LIB = ../common/linux_x86_64/libGLEW.a -lglfw ../common/linux_x86_64/libassimp.a
SYS_LIB = -lGL -lz 
SRC = main.cpp

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${SYS_LIB}

